services:
  expense-tracking-postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: expense_tracking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - expense-tracking-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - expense-tracking-network

  expense-tracking-api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://expense-tracking-postgres:5432/expense_tracking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - expense-tracking-postgres
    networks:
      - expense-tracking-network

volumes:
  expense-tracking-postgres-data:
networks:
  expense-tracking-network:
    driver: bridge